# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '3.1.x'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Application Code'
  jobs:
  - job: 'Build'    
    steps:
    - template: 'deploy/templates/build.yaml'

- stage: Dev
  displayName: 'Deploy to Dev environment'
  dependsOn: Build
  jobs:
    - job: Provision
      displayName: 'Provision Azure Resources'
      variables:
      - group: Release
      steps:
        - template: 'deploy/templates/provision-az-webapp.yaml'
          parameters:
            environment: 'dev'

    - job: MigrateDB
      displayName: 'Run Database Migration'
      variables:
      - name: WebAppName
        value: $[ dependencies.Provision.outputs['RunTerraform.webappname'] ]
      - group: Release
      condition: eq(1,2)
      dependsOn: Provision
      steps:
        - template: 'deploy/templates/migrate-db.yaml'
          parameters:
            environment: 'dev'
            WebAppName: $[ dependencies.Provision.outputs['RunTerraform.webappname'] ]
        
    - deployment: Deploy
      displayName: 'Deploy Application'
      condition: eq(1,2)
      dependsOn: MigrateDB
      environment: 'todoapp-dev'
      variables:
        WebAppName: $[ dependencies.Provision.outputs['RunTerraform.webappname'] ]
      strategy:
        runOnce:
          deploy:
            steps:
              - template: 'deploy/templates/deploy-app.yaml'
                parameters:
                  environment: 'dev'
                  WebAppName: $[ dependencies.Provision.outputs['RunTerraform.webappname'] ]

