steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk $(dotnetSdkVersion)'
    inputs:
      version: '$(dotnetSdkVersion)'

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'
  
  - task: DotNetCoreCLI@2
    displayName: 'Publish & Zip'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: |
        src/TodoApp/*.csproj
      arguments: '--no-build --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'  