parameters:
- name: environment
  type: string

- name: webappname
  type: string

- name: sqlserverfqdn
  type: string

steps:
- script: echo deploy app ${{ parameters.environment }} ${{ parameters.webappname }} ${{ parameters.sqlserverfqdn }}
- task: AzureWebApp@1
  displayName: Azure Web App Deploy
  inputs:
    azureSubscription: 'azure-terraform-spn'
    appName: ${{ parameters.webappname }}
    appType: webAppLinux
    appSettings: -DB_SERVER tcp:${{ parameters.sqlserverfqdn }} -DB_USER $(DbUser) -DB_PASSWORD $(DbPassword) -GREETING "Hello from Azure DevOps"
    package: $(Pipeline.Workspace)/drop/*.zip
