parameters:
- name: environment
  type: string

- name: sqlserverfqdn
  type: string

steps:
- script: echo The value passed in is ${{ parameters.environment }} ${{ parameters.sqlserverfqdn }}

- task: SqlAzureDacpacDeployment@1
  displayName: "Run DB Migration Script"
  inputs:
    azureSubscription: 'azure-terraform-spn'
    serverName: $(DbName)
    databaseName: ${{parameters.sqlserverfqdn}}
    sqlUsername: $(DbUser)
    sqlPassword: $(DbPassword)
    deployType: 'sqlTask'
    sqlFile: '$(Pipeline.Workspace)/drop/dbmigration.sql'