parameters:
- name: environment
  type: string

steps:
- script: |
    # Exit when any command returns a failure status.
    set -e

    # Write backend.tfvars.
    echo 'resource_group_name = "'$(TfStorageAccountResourceGroupName)'"' | tee backend.tfvars
    echo 'storage_account_name = "'$(TfStorageAccountName)'"' | tee -a backend.tfvars
    echo 'container_name = "'$(TfStateContainerName)'"' | tee -a backend.tfvars
    echo 'key = "terraform.tfstate"' | tee -a backend.tfvars
   
    # Initialize Terraform.
    echo "*********** Run Terraform Init"
    terraform init -input=false -backend-config="backend.tfvars" -no-color

    echo "*********** Create or Select Terraform Workspace"

    if [ $(terraform workspace list | grep -c '${{parameters.environment}}') -eq 0 ]
    then
      echo "Creating new workspace $1"
      terraform workspace new '${{parameters.environment}}' -no-color
    else
      echo "Switching to workspace '${{parameters.environment}}'"
      terraform workspace select '${{parameters.environment}}' -no-color
    fi

    # Write terraform.tfvars.
    echo 'prefix = "hashidemo"' | tee terraform.tfvars
    echo 'location = "'$(ResourceGroupLocation)'"' | tee -a terraform.tfvars
    echo 'db_user = "'$(DbUser)'"' | tee -a terraform.tfvars
    echo 'db_password = "'$(DbPassword)'"' | tee -a terraform.tfvars
    echo 'db_name = "'$(DbName)'"' | tee -a terraform.tfvars
    echo 'isp_client_ip = "'$(ISPClientIP)'"' | tee -a terraform.tfvars

    # Create Terraform execution plan
    echo "*********** Run Terraform Validate and Plan"
    terraform validate
    terraform plan -input=false -out=tfplan -no-color

    # Apply the Terraform plan.
    echo "*********** Run Terraform Apply"
    terraform apply -input=false -auto-approve -no-color tfplan

    # Get the App Service name.
    resourcegroupname=$(terraform output resource_group_name)
    sqldatabasename=$(terraform output sql_database_name)
    sqlserverfqdn=$(terraform output sql_server_fqdn)
    webappname=$(terraform output web_app_name)
    webappfqdn=$(terraform output web_app_fqdn)

    # Write the variables to the pipeline.
    echo "##vso[task.setvariable variable=resourcegroupname;isOutput=true]$resourcegroupname"
    echo "##vso[task.setvariable variable=sqldatabasename;isOutput=true]$sqldatabasename"
    echo "##vso[task.setvariable variable=sqlserverfqdn;isOutput=true]$sqlserverfqdn"
    echo "##vso[task.setvariable variable=webappname;isOutput=true]$webappname"
    echo "##vso[task.setvariable variable=webappfqdn;isOutput=true]$webappfqdn"

    rm -f *.tfvars
  name: 'RunTerraform'
  displayName: 'Run Terraform'
  workingDirectory: $(Pipeline.Workspace)/drop/deploy/azure/todoapp-web
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)