apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  labels:
    app: todoapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: todoapp