spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: "todoapp-role"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"        
        vault.hashicorp.com/agent-inject-secret-todoapp.config: "secret/todoapp/config"
        vault.hashicorp.com/agent-inject-template-todoapp.config: |
          {{ with secret "secret/todoapp/config" -}}
          {{ range $k, $v := .Data.data }}
          export {{ $k }}={{ $v }}
          {{ end }}
          {{- end }}